# Infos Agent
pool: 
 name: Default 
 demands: 
  - agent.name -equals AGENTDOCKERTEST 

stages:
- stage: BuildAndDeploy
  displayName: Build and deploy stage
  jobs:
  - job: BuildJob
    steps:
    - checkout: self # checkout de code de project 
    - script: |
        npm install
        ng build
      displayName: 'npm install and build'
    
    - task: FtpUpload@2 # c'est une tache predefinie par Azure pour delpyer le artifact via ftp
      displayName: 'Deploy task via ftp'
      inputs:
        credentialsOption: 'inputs'
        serverUrl: 'ftps://waws-prod-am2-539.ftp.azurewebsites.windows.net/site/wwwroot'
        username: 'CineFrontWebbApp\$CineFrontWebbApp'
        password: '4pYWZKavgCp0KejwMjftjeaA1kdnarvSxmolzih1kkka01K8ZjrFhYmHBTX8'
        rootDirectory: '$(Build.SourcesDirectory)/dist/cinema-front-web'
        filePatterns: '**'
        remoteDirectory: '/site/wwwroot'
        clean: false
        cleanContents: false
        preservePaths: true
        trustSSL: false