pool: 
 name: Default 
 demands: 
  - agent.name -equals AGENTDOCKERTEST

variables:
  environmentName: 'frontendenv'
  webAppName: 'CineFrontWebbApp'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    steps:
    - checkout: self
    - script: |
        npm install
        ng build
      displayName: 'npm install and build'
    
    - task: FtpUpload@2
      displayName: 'Deploy Azure Web App : $(webAppName) '
      inputs:
        credentialsOption: 'inputs'
        serverUrl: 'ftps://waws-prod-am2-539.ftp.azurewebsites.windows.net/site/wwwroot'
        username: 'CineFrontWebbApp\$CineFrontWebbApp'
        password: '4pYWZKavgCp0KejwMjftjeaA1kdnarvSxmolzih1kkka01K8ZjrFhYmHBTX8'
        rootDirectory: '$(Build.SourcesDirectory)/dist/cinema-front-web'
        filePatterns: '**'
        remoteDirectory: '/site/wwwroot'
        clean: false
        cleanContents: false
        preservePaths: true
        trustSSL: false